services:
  eureka-server:
    build: EurekaServer
    ports:
      - 8761:8761

  gateway:
    build: gateway-service
    ports:
      - 7000:7000
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    depends_on: 
      - cuentas-microservice
      - cliente-microservice

  cuentas-microservice:
    build: cuentasservice
    ports:
      - 8002:8002
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/banco_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SERVER_PORT=8002
    depends_on: 
      - mysql
      - rabbitmq
      
  cliente-microservice:
    build: Cliente-service
    ports:
      - 8001:8001
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/banco_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - SERVER_PORT=8001
    depends_on: 
      - cuentas-microservice
      - rabbitmq
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=banco_db
    volumes:
    - ./BaseDatos.sql:/docker-entrypoint-initdb.d/BaseDatos.sql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

