
spring:
  application:
    name: gateway-service
  threads:
    virtual:
      enabled: true
  main:
    web-application-type: reactive

server:
  port: 7000

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
